### ISSUE TITLE
Spanish Translation : Accented letters are misspelled with '?' on the log in page

### ISSUE THREAD

**Issue by Hema-Nambi** [NorthBridge/nexus-community#552] opened 2018-11-14 04:07 UTC
There is a question mark on all the accented letters
![image](https://user-images.githubusercontent.com/30035025/48459612-e6525200-e798-11e8-871d-db3727225ece.png)

**Comment by kdflint** [comment] 2018-11-27 18:02
OK, the root cause for this may well be the same thing that is causing #524. 

This display error is generally caused by character encoding snafoo. However, the language translation object file is confirmed correct. (messages.mo)

When I visit login page and Spanish is my browser-preference, then display is correct. Display is always correct inside site. When I logout, even if Spanish is my browser-preference, then I get question marks instead of accented characters.

Logging out destroys the session, so something in the session is required in order for encoding to be done accurately.

See in the vicinity of src/framework/Util.php::606 to discover what happens with language when a session is initiated.

**Comment by kdflint** [comment] 2019-03-12 21:08
Fixed by waiting to execute `Utilities::setUserLanguageEnv();` until after any logout process is complete. A logout process executes if page is visited with parameter `logout=true`.

Prior we were setting language environment and then immediately wiping it out under a logout scenario.

**Closed by kdflint** 2019-03-12 21:08 UTC
Labels: scoped
